### PR TITLE
Improve documentation

### PR DESCRIPTION
**Pull request by RaulPPelaez**
- [x] Added more information to the documentation of some classes.
- [x] Also added some details to the help you get for charge/spin when running torchmd-train --help
- [x] Fixed black formatting in some files.
- [x] Add a readthedocs webpage

### CODE REVIEW

**Comment by RaulPPelaez** [comment]
I went ahead and started integrating a Sphinx documentation to publish it in https://docs.readthedocs.io/en/stable/
Luckily, this being a python project makes it possible to easily autogenerate most of it from the docstrings. Alas, it requires being careful with the docstring format so sphinx understands it.

Thus far I have a component tree:
image
And doc pages for some of the main classes/functions, which look like this:
image

**Comment by RaulPPelaez** [comment]
This is ready to merge. 
@guillemsimeon @AntonioMirarchi @raimis @giadefa Any comments about how the docs are set up now?
The docs in this PR are (and will be) hosted here https://torchmd-net.readthedocs.io 
- After this is merged ReadTheDocs will pick up on any new release tag and generate a new version automatically, by default the latest one is showed.
- I added a github workflow to check that the docs are building (this is all it does).

If you are ok with it please review/approve the PR so I can merge. In any case comments/suggestion are appreciated.

**Review by raimis — APPROVED** [review]
Looks good!

**Review by guillemsimeon — APPROVED** [review]
Great

**Pull request merged**
