### PR TITLE
Update the installation instructions

### LINKED ISSUE #108: Problem creating an environment
I install torchmd-net as shown in README.md. When I run examples with the command:
`CUDA_VISIBLE_DEVICES=0 python scripts/train.py --conf examples/ET-QM9.yaml`,
 it reports the following errors:

d1bbdee55949643f6c982c56525685d8

Can anyone know the reasons?

### PR DESCRIPTION
**Pull request by raimis**
- [x] Update the installation instructions to circumvent https://github.com/conda-forge/openmm-torch-feedstock/issues/20

Fixes #108

### CODE REVIEW

**Comment by raimis** [comment]
@stefdoerr could you review?

**Comment by stefdoerr** [comment]
The only difference I've seen between mamba and conda is that mamba will ignore channel priority if it finds higher package versions in later channels. Are you sure this is not the case here as well? Because then it could be solved by asking for the right package versions

**Comment by raimis** [comment]
No, it is an issue like in https://github.com/conda-forge/openmm-torch-feedstock/issues/20: `conda` installs an incompatible package with from the same channel.

**Comment by raimis** [comment]
The package priorities isn't an issue, because everything comes from `conda-forge`.

**Review by stefdoerr — APPROVED** [review]

**Pull request merged**
