### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by guillemsimeon**
update readme according to new release

### CODE REVIEW

**Comment by RaulPPelaez** [comment]
Please add it here too https://github.com/torchmd/torchmd-net/edit/main/docs/source/index.rst

**Review by RaulPPelaez — APPROVED** [review]
Great, thanks!

**Comment by guillemsimeon** [comment]
I never remember about these files :)

**Comment by RaulPPelaez** [comment]
It is a tricky business having some information in two places. But the README being the landing page makes it important to keep some of the stuff there too, so...

**Pull request merged**
