### PR TITLE
Update md17

### PR DESCRIPTION
**Pull request by AntonioMirarchi**
The file names used in the MD17 dataloader (torchmdnet/datasets/md17.py) have become obsolete. This pull request (PR) aims to update all the file names in accordance with the latest release available at http://www.quantum-machine.org/gdml/data/npz/.

### CODE REVIEW

**Review by RaulPPelaez — APPROVED** [review]
Looks good to me, always have to change these -.-

**Comment by AntonioMirarchi** [comment]
There is also the possibility to include more datasets like the revised ones.

**Comment by RaulPPelaez** [comment]
Should I merge now or do you want to add those before?

**Comment by AntonioMirarchi** [comment]
I looked closer at the other datasets, and to include them we need to change the dataloader because they are available on a different website and also the single arrays are named differently in the npz files respect to the original ones. So I think you can merge this for the moment

**Pull request merged**
