### PR TITLE
Remove dependency on torch_scatter and torch_sparse

### PR DESCRIPTION
**Pull request by RaulPPelaez**
Removes dependency on torch_sparse by implementing message passing operations with manually written ones.

Removes dependency on torch_scatter by using torch.index_add and torch.scatter_reduce.

### CODE REVIEW

**Comment by RaulPPelaez** [comment]
cc @guillemsimeon @AntonioMirarchi. Correctness tests are passing, but for this PR I had to reimplement the message passing of ET, T, and GN.

I do not want to merge it before a long train has been carried out to compare nothing broke. 
Can you recommend a good test yaml for this? Please post it here and I will run it with/without this PR.

**Comment by guillemsimeon** [comment]
For the ET, the MD17 is fine. For the T, I would directly remove the architecture from TorchMD-NET, and I do not know any case where it has been used. For the GN, you can perhaps use the ones here https://arxiv.org/pdf/2212.07492.pdf

**Comment by RaulPPelaez** [comment]
@giadefa, do you agree with removing the Transformer architecture altogether? Its less dev burden for sure...

**Comment by guillemsimeon** [comment]
Raul, could you also train TensorNet on QM9 U0 with seed 1 as part of these tests? The yaml is in the repo.

**Comment by RaulPPelaez** [comment]
I would say ET is correctly implemented:
image

**Comment by RaulPPelaez** [comment]
TensorNet also looks ok:
image

**Comment by RaulPPelaez** [comment]
GN also seems fine:
image
Not sure what makes GN be so much more accurate in terms of reproducibility than the other ones, though.

**Review by guillemsimeon — APPROVED** [review]
it looks good to me

**Pull request merged**
