### PR TITLE
Use switching function for Coulomb prior

### PR DESCRIPTION
**Pull request by peastman**
Originally I scaled the Coulomb prior by $\text{erfc}(\alpha r)$ to reduce its effect at short distances.  It turned out this didn't work well because it was still too short ranged.  Even at distances of only 1-2 A there was already a large component of Coulomb energy.  I changed it to a cosine switching function which works much better.

### CODE REVIEW

**Comment by peastman** [comment]
I think the test failure was caused by #286.  It's also failing on the main branch.

**Comment by stefdoerr** [comment]
Pull from the main branch, that crash is fixed.

**Comment by stefdoerr** [comment]
Fixed in main now

**Comment by RaulPPelaez** [comment]
Looks good to me. This invalidates checkpoints using the Coulomb prior. I get that it is for the better but it is starting to happen a lot.
We really need to cook versioning into the checkpoints...

**Comment by RaulPPelaez** [comment]
I added the versioning functionality in #288

**Comment by peastman** [comment]
I don't think anyone has ever used the Coulomb prior.  It just didn't work very well.  I wouldn't worry about breaking compatibility with it.

**Comment by peastman** [comment]
Tests are passing now.

**Review by RaulPPelaez — APPROVED** [review]
LGTM Thanks Peter

**Pull request merged**
