### PR TITLE
add arg to MemmappedDataset

### PR DESCRIPTION
**Pull request by AntonioMirarchi**
The AceDataloader (ace.py) is referring to MemmappDataset as super class and it's complaining about `remove_ref_energy` arg when it's initialized. This small change, it's fixing it.

### CODE REVIEW

**Comment by RaulPPelaez** [comment]
MemmappedDataset should not have an argument called remove_ref_energy.
Same with AceDataloader

**Comment by AntonioMirarchi** [comment]
ok so should I just remove them from both?

**Comment by RaulPPelaez** [comment]
Yes! I see we do not have any test referencing Ace, It would be great to have one that at least creates it, so this does not happen again.

The docstring has an example usage. Would you add it to test_datasets.py?

```python
import numpy as np
from torchmdnet.datasets import Ace
import h5py
# Version 1.0 example
with h5py.File("molecule.h5", 'w') as f:
    f.attrs["layout"] = "Ace"
    f.attrs["layout_version"] = "1.0"
    f.attrs["name"] = "sample_molecule_data"
    for m in range(3):  # Three molecules
        mol = f.create_group(f"mol_{m+1}")
        mol["atomic_numbers"] = [1, 6, 8]  # H, C, O
        mol["formal_charges"] = [0, 0, 0]  # Neutral charges
        confs = mol.create_group("conformations")
        for i in range(2):  # Two conformations
            conf = confs.create_group(f"conf_{i+1}")
            conf["positions"] = np.random.random((3, 3))
            conf["positions"].attrs["units"] = "Å"
            conf["formation_energy"] = np.random.random()
            conf["formation_energy"].attrs["units"] = "eV"
            conf["forces"] = np.random.random((3, 3))
            conf["forces"].attrs["units"] = "eV/Å"
            conf["partial_charges"] = np.random.random(3)
            conf["partial_charges"].attrs["units"] = "e"
            conf["dipole_moment"] = np.random.random(3)
            conf["dipole_moment"].attrs["units"] = "e*Å"
dataset = Ace(root=".", paths="molecule.h5")
assert len(dataset) == 6
dataset = Ace(root=".", paths=["molecule.h5", "molecule.h5"])
assert len(dataset) == 12
# Version 2.0 example
with h5py.File("molecule_v2.h5", 'w') as f:
    f.attrs["layout"] = "Ace"
    f.attrs["layout_version"] = "2.0"
    f.attrs["name"] = "sample_molecule_data_v2"
    master_mol_group = f.create_group("master_molecule_group")
    for m in range(3):  # Three molecules
        mol = master_mol_group.create_group(f"mol_{m+1}")
        mol["atomic_numbers"] = [1, 6, 8]  # H, C, O
        mol["formal_charges"] = [0, 0, 0]  # Neutral charges
        mol["positions"] = np.random.random((2, 3, 3))  # Two conformations
        mol["positions"].attrs["units"] = "Å"
        mol["formation_energies"] = np.random.random(2)
        mol["formation_energies"].attrs["units"] = "eV"
        mol["forces"] = np.random.random((2, 3, 3))
        mol["forces"].attrs["units"] = "eV/Å"
        mol["partial_charges"] = np.random.random((2, 3))
        mol["partial_charges"].attrs["units"] = "e"
        mol["dipole_moment"] = np.random.random((2, 3))
        mol["dipole_moment"].attrs["units"] = "e*Å"
dataset_v2 = Ace(root=".", paths="molecule_v2.h5")
assert len(dataset_v2) == 6
dataset_v2 = Ace(root=".", paths=["molecule_v2.h5", "molecule_v2.h5"])
assert len(dataset_v2) == 12
```

**Comment by RaulPPelaez** [comment]
Thanks Antonio, this is great!

**Review by RaulPPelaez — APPROVED** [review]

**Pull request merged**
